name: Run Unit Tests of Web App

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "release*"

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies for frontend
        run: |
          cd ./frontend
          yarn install

      - name: Run tests for frontend
        run: |
          cd ./frontend
          yarn test

  test_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies for web
        run: |
          cd ./web
          yarn install

      - name: Run tests for web
        run: |
          cd ./web
          yarn test
